# Generated by Django 4.2.3 on 2023-09-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddIngredientToRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес ингредиента грамм')),
                ('kcal', models.FloatField(editable=False, verbose_name='Калорийность')),
                ('fats', models.FloatField(editable=False, verbose_name='Жиры')),
                ('squirrels', models.FloatField(editable=False, verbose_name='Белки')),
                ('carbs', models.FloatField(editable=False, verbose_name='Углеводы')),
            ],
            options={
                'verbose_name': 'рецепт и ингредиент',
                'verbose_name_plural': 'Состав рецептов',
                'db_table': 'add_ingredient_to_recipe',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ingredient', models.CharField(max_length=30, verbose_name='Наименование')),
                ('kcal', models.IntegerField(verbose_name='Калорийность на 100г')),
                ('fats', models.FloatField(verbose_name='Жиры на 100г')),
                ('squirrels', models.FloatField(verbose_name='Белки на 100г')),
                ('carbs', models.FloatField(verbose_name='Углеводы на 100г')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50, verbose_name='Название рецепта')),
                ('serving_weight', models.IntegerField(verbose_name='Вес порции грамм')),
                ('kcal', models.FloatField(editable=False, verbose_name='Калорийность')),
                ('fats', models.FloatField(editable=False, verbose_name='Жиры')),
                ('squirrels', models.FloatField(editable=False, verbose_name='Белки')),
                ('carbs', models.FloatField(editable=False, verbose_name='Углеводы')),
                ('needed_for_dishes', models.ManyToManyField(through='recipes.AddIngredientToRecipe', to='recipes.ingredients')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'recipes',
            },
        ),
        migrations.AddField(
            model_name='addingredienttorecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='addingredienttorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Рецепт'),
        ),
    ]
