# Generated by Django 4.2.3 on 2023-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresse', models.CharField(db_index=True, max_length=250, verbose_name='Адрес ресторана')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'Адреса ресторанов',
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70, verbose_name='Город')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города обслуживания',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('registration_form', models.CharField(max_length=50, verbose_name='Форма регистрации')),
                ('organization_name', models.CharField(max_length=50, verbose_name='Название организации')),
                ('INN', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('OGRN', models.PositiveBigIntegerField(verbose_name='ОГРН')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('addresses', models.ManyToManyField(to='organization.addresses', verbose_name='Адреса ресторанов')),
            ],
            options={
                'verbose_name': 'руководителя',
                'verbose_name_plural': 'О руководителе',
                'db_table': 'about_manager',
            },
        ),
    ]
