# Generated by Django 5.0.1 on 2024-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'Адреса производств'},
        ),
        migrations.AddField(
            model_name='addresses',
            name='working_time',
            field=models.CharField(max_length=16, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='addresse',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Адрес производственной точки'),
        ),
        migrations.AlterField(
            model_name='deliveryservice',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
