# Generated by Django 5.0.1 on 2024-01-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('queue', models.IntegerField(verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'категорию ',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'menu_categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/%Y/%m/%d/', verbose_name='Изображение')),
                ('product_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('shelf_life', models.IntegerField(choices=[(1, '5 суток при температуре от +2 до +5 °C'), (2, '48 часов при температуре от +2 до +5 °C'), (3, '72 часа при температуре от +2 до +5 °C')], default=0, verbose_name='Срок годности')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('queue', models.IntegerField(default=0, editable=False, verbose_name='Популярность')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('publication', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('cities', models.ManyToManyField(to='organization.cities', verbose_name='Города обслуживания')),
                ('menu_categories', models.ManyToManyField(to='shop_app.menucategories', verbose_name='Категория товара')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Продукция',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
    ]
