# Generated by Django 4.2.3 on 2023-08-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(db_index=True, max_length=20, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('queue', models.IntegerField(verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'категорию ',
                'verbose_name_plural': 'Категории блюд',
                'db_table': 'menu_categories',
            },
        ),
        migrations.CreateModel(
            name='SettingsShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('currency', models.CharField(max_length=5, verbose_name='Валюта')),
                ('vat', models.IntegerField(verbose_name='Код ставки НДС')),
            ],
            options={
                'verbose_name': 'настройки магазина ',
                'verbose_name_plural': 'Настройки',
                'db_table': 'settings_shop',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/%Y/%m/%d/', verbose_name='Изображение')),
                ('product_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('shelf_life', models.IntegerField(choices=[(0, '---------'), (1, '5 суток при температуре от +2 до +5 °C'), (2, '48 часов при температуре от +2 до +5 °C'), (2, '72 часа при температуре от +2 до +5 °C')], default=0, verbose_name='Срок годности')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('queue', models.IntegerField(default=0, editable=False, verbose_name='Очередность')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обнавлено')),
                ('publication', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('cities', models.ManyToManyField(to='organization.cities', verbose_name='Города обслуживания')),
                ('menu_categories', models.ManyToManyField(to='shop_app.menucategories', verbose_name='Категория блюда')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'блюда',
                'verbose_name_plural': 'Продукция',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
    ]
